version: "2.4"

services:

  explorer:
    container_name: blockcore-paperwallet
    image: nginx
    mem_limit: 256m
    cpus: 0.200
    environment:
      VIRTUAL_HOST: paperwallet.blockcore.net
      VIRTUAL_PORT: 80
      VIRTUAL_NETWORK: proxy
      VIRTUAL_PROTO: http
      LETSENCRYPT_HOST: paperwallet.blockcore.net
      LETSENCRYPT_EMAIL: admin@blockcore.net
    restart: unless-stopped
    volumes:
      - /home/blockcore/src/blockcore-paperwallet:/usr/share/nginx/html
    # ports:
    #   - 8088:80
    networks:
      - proxy
networks:
  proxy:
    external: true
    name: proxy